# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-12 13:01
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industry', '0003_industry_parent_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industry',
            name='parent_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), null=True, size=None),
        ),
    ]
