# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-13 04:18
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industry', '0004_auto_20180212_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industry',
            name='industry_id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='industry',
            name='parent_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), null=True, size=None),
        ),
    ]
