# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-13 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industry', '0005_auto_20180213_0418'),
    ]

    operations = [
        migrations.AddField(
            model_name='industry',
            name='direct_parent_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
